// <auto-generated />
using Alhadis.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alhadis.Migrations
{
    [DbContext(typeof(HadithDbContext))]
    [Migration("20250601205314_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alhadis.Models.Hadith", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("WeekId", "LanguageId")
                        .IsUnique();

                    b.ToTable("Hadiths");
                });

            modelBuilder.Entity("Alhadis.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Arapça"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oromiçe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amhariçe"
                        });
                });

            modelBuilder.Entity("Alhadis.Models.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("Months");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonthName = "Ocak",
                            YearId = 1
                        },
                        new
                        {
                            Id = 2,
                            MonthName = "Şubat",
                            YearId = 1
                        },
                        new
                        {
                            Id = 3,
                            MonthName = "Mart",
                            YearId = 1
                        },
                        new
                        {
                            Id = 4,
                            MonthName = "Nisan",
                            YearId = 1
                        },
                        new
                        {
                            Id = 5,
                            MonthName = "Mayıs",
                            YearId = 1
                        },
                        new
                        {
                            Id = 6,
                            MonthName = "Haziran",
                            YearId = 1
                        },
                        new
                        {
                            Id = 7,
                            MonthName = "Temmuz",
                            YearId = 1
                        },
                        new
                        {
                            Id = 8,
                            MonthName = "Ağustos",
                            YearId = 1
                        },
                        new
                        {
                            Id = 9,
                            MonthName = "Eylül",
                            YearId = 1
                        },
                        new
                        {
                            Id = 10,
                            MonthName = "Ekim",
                            YearId = 1
                        },
                        new
                        {
                            Id = 11,
                            MonthName = "Kasım",
                            YearId = 1
                        },
                        new
                        {
                            Id = 12,
                            MonthName = "Aralık",
                            YearId = 1
                        });
                });

            modelBuilder.Entity("Alhadis.Models.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MonthId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("Weeks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonthId = 1,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            MonthId = 1,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            MonthId = 1,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            MonthId = 1,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            MonthId = 2,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 6,
                            MonthId = 2,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 7,
                            MonthId = 2,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 8,
                            MonthId = 2,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 9,
                            MonthId = 3,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 10,
                            MonthId = 3,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 11,
                            MonthId = 3,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 12,
                            MonthId = 3,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 13,
                            MonthId = 4,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 14,
                            MonthId = 4,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 15,
                            MonthId = 4,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 16,
                            MonthId = 4,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 17,
                            MonthId = 5,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 18,
                            MonthId = 5,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 19,
                            MonthId = 5,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 20,
                            MonthId = 5,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 21,
                            MonthId = 6,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 22,
                            MonthId = 6,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 23,
                            MonthId = 6,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 24,
                            MonthId = 6,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 25,
                            MonthId = 7,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 26,
                            MonthId = 7,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 27,
                            MonthId = 7,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 28,
                            MonthId = 7,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 29,
                            MonthId = 8,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 30,
                            MonthId = 8,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 31,
                            MonthId = 8,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 32,
                            MonthId = 8,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 33,
                            MonthId = 9,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 34,
                            MonthId = 9,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 35,
                            MonthId = 9,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 36,
                            MonthId = 9,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 37,
                            MonthId = 10,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 38,
                            MonthId = 10,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 39,
                            MonthId = 10,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 40,
                            MonthId = 10,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 41,
                            MonthId = 11,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 42,
                            MonthId = 11,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 43,
                            MonthId = 11,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 44,
                            MonthId = 11,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 45,
                            MonthId = 12,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 46,
                            MonthId = 12,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 47,
                            MonthId = 12,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 48,
                            MonthId = 12,
                            WeekNumber = 4
                        });
                });

            modelBuilder.Entity("Alhadis.Models.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("YearNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Years");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            YearNumber = 2025
                        });
                });

            modelBuilder.Entity("Alhadis.Models.Hadith", b =>
                {
                    b.HasOne("Alhadis.Models.Language", "Language")
                        .WithMany("Hadiths")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alhadis.Models.Week", "Week")
                        .WithMany("Hadiths")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Alhadis.Models.Month", b =>
                {
                    b.HasOne("Alhadis.Models.Year", "Year")
                        .WithMany("Months")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Year");
                });

            modelBuilder.Entity("Alhadis.Models.Week", b =>
                {
                    b.HasOne("Alhadis.Models.Month", "Month")
                        .WithMany("Weeks")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");
                });

            modelBuilder.Entity("Alhadis.Models.Language", b =>
                {
                    b.Navigation("Hadiths");
                });

            modelBuilder.Entity("Alhadis.Models.Month", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("Alhadis.Models.Week", b =>
                {
                    b.Navigation("Hadiths");
                });

            modelBuilder.Entity("Alhadis.Models.Year", b =>
                {
                    b.Navigation("Months");
                });
#pragma warning restore 612, 618
        }
    }
}
